// 管理员密码选择配置
export const LOGIN_TYPES_MAP = {
  random: {
    label: '随机生成',
    key: 'random',
  },
  keypair: {
    label: '关联密钥',
    key: 'keypair',
  },
  image: {
    label: '保留镜像设置',
    key: 'image',
  },
  password: {
    label: '手工输入',
    key: 'password',
  },
}

export const RDS_ACCOUNT_PRIVILEGES = {
  rw: '读写',
  r: '只读',
  ddl: '仅DDL',
  dml: '仅DML',
  owner: '所有者',
  custom: '自定义',
}

export const RDS_MONITOR_OPTS = {
  aliyun: [
    {
      name: 'cpu',
      label: 'CPU使用率',
      seleteItem: 'usage_active',
      fromItem: 'rds_cpu',
      as: 'CPU使用率',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'mem',
      label: '内存使用率',
      seleteItem: 'used_percent',
      fromItem: 'rds_mem',
      as: '内存使用率',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'disk',
      label: '磁盘使用率',
      seleteItem: 'used_percent',
      as: '磁盘使用率',
      fromItem: 'rds_disk',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'mysql_bps_recv',
      label: 'Mysql网络入流量',
      seleteItem: 'bps_recv',
      fromItem: 'rds_netio',
      as: 'Mysql网络入流量',
      unit: 'bps',
      transfer: 1000,
      tags: {
        tag: 'mysql',
      },
    },
    {
      name: 'mysql_bps_sent',
      label: 'Mysql网络出流量',
      seleteItem: 'bps_sent',
      as: 'Mysql网络出流量',
      fromItem: 'rds_netio',
      unit: 'bps',
      transfer: 1000,
      tags: {
        tag: 'mysql',
      },
    },
    {
      name: 'mysql_bps_recv',
      label: 'SQLServer网络入流量',
      seleteItem: 'bps_recv',
      fromItem: 'rds_netio',
      as: 'SQLServer网络入流量',
      unit: 'bps',
      transfer: 1000,
      tags: {
        tag: 'sqlserver',
      },
    },
    {
      name: 'sql_bps_sent',
      label: 'SQLServer网络出流量',
      seleteItem: 'bps_sent',
      as: 'SQLServer网络出流量',
      fromItem: 'rds_netio',
      unit: 'bps',
      transfer: 1000,
      tags: {
        tag: 'sqlserver',
      },
    },
    {
      name: 'conn',
      label: '连接数使用率',
      seleteItem: 'usage_active',
      as: '磁盘使用率',
      fromItem: 'rds_conn',
      unit: '%',
      transfer: 1,
    },
  ],
  huawei: [
    {
      name: 'cpu',
      label: 'CPU使用率',
      seleteItem: 'usage_active',
      fromItem: 'rds_cpu',
      as: 'CPU使用率',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'mem',
      label: '内存使用率',
      seleteItem: 'used_percent',
      fromItem: 'rds_mem',
      as: '内存使用率',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'bps_recv',
      label: '网络入流量',
      seleteItem: 'bps_recv',
      fromItem: 'rds_netio',
      as: '网络入流量',
      unit: 'bps',
      transfer: 1024,
    },
    {
      name: 'bps_sent',
      label: '网络出流量',
      seleteItem: 'bps_sent',
      as: '网络出流量',
      fromItem: 'rds_netio',
      unit: 'bps',
      transfer: 1024,
    },
    {
      name: 'disk',
      label: '磁盘使用率',
      seleteItem: 'used_percent',
      as: '磁盘使用率',
      fromItem: 'rds_disk',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'conn',
      label: '连接数使用率',
      seleteItem: 'usage_active',
      as: '磁盘使用率',
      fromItem: 'rds_conn',
      unit: '%',
      transfer: 1,
    },
  ],
}

export const REDIS_MONITOR_OPTS = {
  aliyun: [
    {
      name: 'cpu',
      label: 'CPU使用率',
      seleteItem: 'usage_percent',
      fromItem: 'dcs_cpu',
      as: 'CPU使用率',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'mem',
      label: '内存使用率',
      seleteItem: 'used_percent',
      fromItem: 'dcs_mem',
      as: '内存使用率',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'dcs_bps_recv',
      label: '网络瞬时输入流量',
      seleteItem: 'bps_recv',
      fromItem: 'dcs_netio',
      as: '网络瞬时输入流量',
      unit: 'bps',
      transfer: 1000,
    },
    {
      name: 'dcs_bps_sent',
      label: '网络瞬时输出流量',
      seleteItem: 'bps_sent',
      as: '网络瞬时输出流量',
      fromItem: 'dcs_netio',
      unit: 'bps',
      transfer: 1000,
    },

    {
      name: 'used_conn',
      label: '活跃客户端数量',
      seleteItem: 'used_conn',
      as: '活跃客户端数量',
      fromItem: 'used_conn',
      unit: '',
      transfer: 1,
    },
    {
      name: 'opt_sec',
      label: '每秒并发操作数',
      seleteItem: 'opt_sec',
      as: '每秒并发操作数',
      fromItem: 'dcs_instantopt',
      unit: '',
      transfer: 1,
    },
    {
      name: 'key_count',
      label: '缓存键总数',
      seleteItem: 'key_count',
      as: '缓存键总数',
      fromItem: 'dcs_cachekeys',
      unit: '',
      transfer: 1,
    },
    {
      name: 'key_count',
      label: '已过期的键总数',
      seleteItem: 'key_count',
      as: '已过期的键总数',
      fromItem: 'dcs_cachekeys',
      unit: '',
      transfer: 1,
      tags: {
        exp: 'expire',
      },
    },
    {
      name: 'used_byte',
      label: '数据集使用内存',
      seleteItem: 'used_byte',
      as: '数据集使用内存',
      fromItem: 'dcs_datamem',
      unit: '',
      transfer: 1024,
    },
  ],
  huawei: [
    {
      name: 'cpu',
      label: 'CPU使用率',
      seleteItem: 'usage_percent',
      fromItem: 'dcs_cpu',
      as: 'CPU使用率',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'mem',
      label: '内存使用率',
      seleteItem: 'used_percent',
      fromItem: 'dcs_mem',
      as: '内存使用率',
      unit: '%',
      transfer: 1,
    },
    {
      name: 'bps_recv',
      label: '网络瞬时输入流量',
      seleteItem: 'bps_recv',
      fromItem: 'dcs_netio',
      as: '网络瞬时输入流量',
      unit: 'bps',
      transfer: 1000,
    },
    {
      name: 'bps_sent',
      label: '网络瞬时输出流量',
      seleteItem: 'bps_sent',
      as: '网络瞬时输出流量',
      fromItem: 'dcs_netio',
      unit: 'bps',
      transfer: 1000,
    },
    {
      name: 'used_conn',
      label: '活跃客户端数量',
      seleteItem: 'used_conn',
      as: '磁盘使用率',
      fromItem: 'dcs_conn',
      unit: '',
      transfer: 1,
    },
    {
      name: 'conn',
      label: '每秒并发操作数',
      seleteItem: 'opt_sec',
      as: '每秒并发操作数',
      fromItem: 'dcs_instantopt',
      unit: '',
      transfer: 1,
    },
    {
      name: 'keys',
      label: '缓存键总数',
      seleteItem: 'key_count',
      as: '缓存键总数',
      fromItem: 'dcs_cachekeys',
      unit: '',
      transfer: 1,
    },
    {
      name: 'expires',
      label: '已过期的键总数',
      seleteItem: 'key_count',
      as: '已过期的键总数',
      fromItem: 'dcs_cachekeys',
      unit: '',
      transfer: 1,
      tags: {
        tag: 'expire',
      },
    },
    {
      name: 'used_memory_dataset',
      label: '数据集使用内存',
      seleteItem: 'used_byte',
      as: '数据集使用内存',
      fromItem: 'dcs_datamem',
      unit: 'B',
      transfer: 1024,
    },
  ],
}
