import { metricItems } from '@Compute/views/node-alert/constants'
import i18n from '@/locales'

// 容器主机监控数据
export const POD_MONITOR = [
  {
    name: 'pod_cpu',
    label: i18n.t('compute.text_523'),
    seleteItem: 'usage_rate',
    fromItem: 'pod_cpu',
    unit: '%',
    transfer: 1,
    metric: metricItems['pod_cpu.usage_rate'].key,
  },
  {
    name: 'pod_mem',
    label: i18n.t('compute.text_518'),
    seleteItem: 'usage_rate',
    fromItem: 'pod_mem',
    unit: '%',
    transfer: 1,
    metric: metricItems['pod_mem.usage_rate'].key,
  },
  {
    name: 'pod_mem',
    label: i18n.t('compute.container.monitor.pod_mem_used'),
    seleteItem: 'working_set_bytes',
    fromItem: 'pod_mem',
    unit: 'B',
    transfer: 1024,
    metric: metricItems['pod_mem.working_set_bytes'].key,
  },
  {
    name: 'pod_volume',
    label: i18n.t('compute.container.monitor.pod_volume_total'),
    seleteItem: 'total',
    fromItem: 'pod_volume',
    unit: 'B',
    transfer: 1024,
    metric: metricItems['pod_volume.total'].key,
  },
  {
    name: 'pod_volume',
    label: i18n.t('compute.container.monitor.pod_volume_used'),
    seleteItem: 'used',
    fromItem: 'pod_volume',
    unit: 'B',
    transfer: 1024,
    metric: metricItems['pod_volume.used'].key,
  },
  {
    name: 'pod_volume',
    label: i18n.t('compute.container.monitor.pod_volume_used_percent'),
    seleteItem: 'used_percent',
    fromItem: 'pod_volume',
    unit: '%',
    transfer: 1,
    metric: metricItems['pod_volume.used_percent'].key,
  },
  {
    name: 'pod_netio',
    label: i18n.t('compute.container.monitor.pod_netio_bps_recv'),
    seleteItem: 'bps_recv',
    fromItem: 'pod_netio',
    unit: 'bps',
    transfer: 1024,
    metric: metricItems['pod_netio.bps_recv'].key,
  },
  {
    name: 'pod_netio',
    label: i18n.t('compute.container.monitor.pod_netio_bps_sent'),
    seleteItem: 'bps_sent',
    fromItem: 'pod_netio',
    unit: 'bps',
    transfer: 1024,
    metric: metricItems['pod_netio.bps_sent'].key,
  },
  {
    name: 'pod_netio',
    label: i18n.t('compute.container.monitor.pod_netio_pps_sent'),
    seleteItem: 'pps_sent',
    fromItem: 'pod_netio',
    transfer: 1,
    unit: 'pps',
    metric: metricItems['pod_netio.pps_sent'].key,
  },
  {
    name: 'pod_netio',
    label: i18n.t('compute.container.monitor.pod_netio_pps_recv'),
    seleteItem: 'pps_recv',
    fromItem: 'pod_netio',
    transfer: 1,
    unit: 'pps',
    metric: metricItems['pod_netio.pps_recv'].key,
  },
]
