import i18n from '@/locales'
const options = [
  {
    label: i18n.t('dashboard.text_78'),
    desc: i18n.t('dashboard.text_79'),
    icon: 'dashboard-number',
    h: 6,
    w: 8,
    component: 'NumberCard',
  },
  {
    label: i18n.t('dashboard.text_80'),
    desc: i18n.t('dashboard.text_81'),
    icon: 'dashboard-usage',
    h: 5,
    w: 10,
    component: 'Ring',
  },
  {
    label: i18n.t('dashboard.text_19'),
    desc: i18n.t('dashboard.text_84'),
    icon: 'dashboard-notice',
    h: 4,
    w: 8,
    component: 'Notify',
  },
  {
    label: 'TOP5',
    desc: i18n.t('dashboard.text_85'),
    icon: 'dashboard-top5',
    h: 8,
    w: 8,
    component: 'Top5',
  },
  {
    label: i18n.t('dashboard.text_17'),
    desc: i18n.t('dashboard.text_86'),
    icon: 'dashboard-log',
    h: 9,
    w: 9,
    component: 'Log',
  },
  {
    label: i18n.t('dashboard.text_47'),
    desc: i18n.t('dashboard.text_83'),
    icon: 'dashboard-suggest-detail',
    h: 5,
    w: 13,
    component: 'SuggestsysAlertsDetail',
  },
  {
    label: i18n.t('dashboard.text_54'),
    desc: i18n.t('dashboard.text_82'),
    icon: 'dashboard-suggest-overview',
    h: 8,
    w: 8,
    component: 'SuggestsysAlertsOverview',
  },
  {
    label: i18n.t('dashboard.text_91'),
    desc: i18n.t('dashboard.text_92'),
    icon: 'dashboard-quota',
    h: 6,
    w: 10,
    scope: ['domain', 'system'],
    component: 'Quota',
  },
  {
    label: i18n.t('dashboard.text_91'),
    desc: i18n.t('dashboard.text_92'),
    icon: 'dashboard-quota',
    h: 6,
    w: 10,
    scope: ['project'],
    component: 'ProjectQuota',
  },
  {
    label: i18n.t('monitor.overview_alert_sum'),
    desc: '',
    h: 5,
    w: 9,
    icon: 'dashboard-alert-sum',
    component: 'UnrecoveredAlarm',
  },
  {
    label: i18n.t('dashboard.consumption_percent'),
    desc: i18n.t('dashboard.consumption_percent_info'),
    h: 6,
    w: 8,
    icon: 'dashboard-consumption-percent',
    component: 'ConsumptionPercent',
  },
  {
    label: i18n.t('dashboard.consmption_trend'),
    desc: '',
    h: 6,
    w: 12,
    icon: 'dashboard-consmption-trend',
    component: 'ConsumptionTrend',
  },
  {
    label: i18n.t('dashboard.vm_history_count'),
    desc: '',
    h: 6,
    w: 12,
    icon: 'dashboard-vmhistory-count-trend',
    component: 'VmHistoryCount',
  },
  {
    label: i18n.t('dashboard.alerts_trend'),
    desc: '',
    h: 6,
    w: 12,
    icon: 'dashboard-alerts-trend',
    component: 'AlertsTrend',
  },
  {
    label: i18n.t('dashboard.cloud_account_health'),
    desc: '',
    h: 7,
    w: 9,
    icon: 'dashboard-cloud-account-health',
    scope: ['system', 'domain'],
    component: 'AccountHealth',
  },
  {
    label: i18n.t('dashboard.userinfo'),
    desc: '',
    h: 7,
    w: 8,
    icon: 'dashboard-user-info',
    component: 'UserInfo',
  },
  {
    label: i18n.t('dashborad.server_numbers'),
    desc: '',
    icon: 'dashboard-suggest-detail',
    h: 5,
    w: 8,
    component: 'ServerNumberDetail',
  },
  {
    label: i18n.t('dashboard.optimization_suggestion'),
    desc: '',
    icon: 'icon_optimization',
    h: 7,
    w: 10,
    component: 'OptimizationSuggestion',
  },
  {
    label: i18n.t('dashboard.monitor'),
    desc: '',
    icon: 'icon_vnc',
    h: 7,
    w: 12,
    component: 'MonitorInfo',
  },
  {
    label: i18n.t('dashboard.UserCount'),
    desc: '',
    icon: 'dashboard-number',
    h: 6,
    w: 8,
    component: 'UserCount',
  },
]

export default options
