const options = [
  {
    label: '数字图',
    desc: '某项指标的统计数字',
    icon: 'dashboard-number',
    h: 2,
    w: 5,
    component: 'NumberCard',
  },
  {
    label: '使用率',
    desc: '某个资源的使用率',
    icon: 'dashboard-usage',
    h: 3,
    w: 5,
    component: 'Ring',
  },
  {
    label: '费用优化总览',
    desc: '本月预估成本和费用优化总览',
    icon: 'dashboard-usage',
    h: 4,
    w: 4,
    component: 'SuggestsysAlertsOverview',
  },
  {
    label: '费用优化资源类型成本分布',
    desc: '费用优化资源列表的资源类型分布',
    icon: 'dashboard-usage',
    h: 4,
    w: 6,
    component: 'SuggestsysAlertsDetail',
  },
  {
    label: '公告',
    desc: '管理员发的系统公告',
    icon: 'dashboard-notice',
    h: 4,
    w: 5,
    component: 'Notify',
  },
  {
    label: 'TOP5',
    desc: '某项指标排名前5',
    icon: 'dashboard-top5',
    h: 5,
    w: 4,
    component: 'Top5',
  },
  {
    label: '操作日志',
    desc: '显示最近的系统操作日志',
    icon: 'dashboard-log',
    h: 5,
    w: 4,
    component: 'Log',
  },
  {
    label: '费用总览',
    desc: '历史费用总览',
    icon: 'dashboard-fee',
    h: 5,
    w: 10,
    component: 'BillHistoryLine',
  },
  {
    label: '资源总览',
    desc: '历史资源总览',
    icon: 'dashboard-resource',
    h: 5,
    w: 10,
    component: 'ResourceHistoryLine',
  },
  {
    label: '配额',
    desc: '配额使用情况',
    icon: 'dashboard-quota',
    h: 7,
    w: 5,
    scope: ['domain', 'system'],
    component: 'Quota',
  },
]

export default options
